### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#102]
Can we give the same treatment to the acknowledgements that we did to QRiS please. 

Text acknowledgements with active hyperlinks. No images.

<img width="673" alt="Screenshot 2024-01-29 at 1 31 28 PM" src="https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/cd070311-0222-4657-99c0-01088fa83694">

**Comment by KellyMWhitehead** [comment]
0.9.1
