### ISSUE TITLE
Incsistent Options Naming

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#103]
In the QViewer help menu there is an item with the label "Settings" that opens a form with the title "Options". Pick one and be consistent. Make sure its the same as QRiS.

Also note that the URL for the help has changed from `rave.riverscapes.net` to [https://viewer.riverscapes.net](https://viewer.riverscapes.net)

**Comment by KellyMWhitehead** [comment]
Both issues fixed for 0.9.1.

QRV still uses the ui files, we should update these to pure python at some point. Fortunately there aren't very many forms (compared to QRiS!).
