### ISSUE TITLE
Wrong Help Link!

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRAVEPlugin#104]
![image](https://github.com/Riverscapes/QRAVEPlugin/assets/9723905/0330af93-8262-4bfc-8d8e-5b2e9a5779b2)
The Help link for new QViewer is wrong! It still links to: https://rave.riverscapes.net.... ALSO @MattReimer we need that HTML redirect to mitigate that one ASAP (see: https://github.com/Riverscapes/RaveAddIn/issues/189). However, this should be fixed to https://viewer.riverscapes.net.

**Comment by KellyMWhitehead** [comment]
Fixed for 0.9.1

**Comment by MattReimer** [comment]
confirmed.
