### ISSUE TITLE
Basemaps not working (for some people)

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#109]
Basemaps were not working for about half the participants in the SLC BLM workshpp. This was affecting me personally (But I think not affecting @KellyMWhitehead).

This urgently needs a fix.

This also needs to working in QRiS as well as the viewer.

**Comment by KellyMWhitehead** [comment]
A change in QGIS after 3.28 is causing this issue. The URI is not converting certain characters (at least "/" and ":", but not "}" in the url. I have a fix pending in QRV.

**Comment by KellyMWhitehead** [comment]
This was fixed in 0.9.1
