### ISSUE TITLE
View in Warehouse menu item is broken

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#111]
Just downloaded project from warehouse. The project.rs.xml file has the warehouse XML entry. But the right click menu in Q is still greyed out.

![image](https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/065d3a9d-4f6d-4844-8e1c-d33c05ca0985)

![image (1)](https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/0064f229-912d-4e9e-a1a6-c7f51621d28b)

**Comment by KellyMWhitehead** [comment]
Fixed for version 0.9.1
