### ISSUE TITLE
Error when Opening Project in Riverscapes Viewer 0.9.1 

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRAVEPlugin#114]
I can't seem to open projects in Riverscapes Viewer without getting this error (Screenshot #1). I have tried uninstalling and reinstalling Riverscapes Viewer and have tried the tool in two different versions of QGIS (3.28.4 & 3.36.0). 

Screenshot #1
![Riverscapes Viewer Error](https://github.com/Riverscapes/QRAVEPlugin/assets/150490067/b48b842a-8512-4b38-806b-e107eb26a58f)

**Comment by Jdgilby** [comment]
@KellyMWhitehead Ive had this same issue as well

**Comment by MattReimer** [comment]
It would be really helpful to have the project you're trying to load or even just the `project.rs.xml` file.

**Comment by Jdgilby** [comment]
@MattReimer @KellyMWhitehead  Here's one that's not working for me.
https://drive.google.com/file/d/1tq6mIz8EyYVmifxO3lIQIUT0bw4zm4M4/view?usp=drive_link

**Comment by MattReimer** [comment]
This should be handled in the next version of the plugin. I'll leave this open until we publish.

**Comment by MattReimer** [comment]
Ok. this should be fixed in 0.9.2
