### ISSUE TITLE
Uploader paths in Windows

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRAVEPlugin#118]
Uploader using wrong slash for paths in windows and not recognizing existing files resulting in deleting/overwriting.

[RiverscapesViewer-Upload.log](https://github.com/Riverscapes/QRAVEPlugin/files/15080694/RiverscapesViewer-Upload.log)

**Comment by MattReimer** [comment]
Slashes were an easy fix. This should be fixed now.
