### ISSUE TITLE
Uploader login issues

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRAVEPlugin#119]
Experienced the following behavior when using Uploader in Windows:

1. When launching uploader, the login browser page appeared and I used the login (via Google account). The browser then displayed: ```This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE```

All subsequent attempts resulted in the same browser message. 

2. Uploader form was stuck in "Browser Login" status. 
![image](https://github.com/Riverscapes/QRAVEPlugin/assets/10746997/b7866edc-92c6-4a94-b483-aad38bdb85c1)

3. After 10-20 seconds, I closed the form, assuming the login had failed. The Refresh Token Task was still running (~60seconds), and I had attempted to cancel/stop this task unsuccessfully. I would then force close QGIS to end the task.

4. After further attempts at running the Uploader, I discovered that the Login process was indeed working, just taking 1-2min to complete and update the form.

The primary issue is that the user is under the impression that a lengthy login process has failed and stuck running in the background.

**Comment by MattReimer** [comment]
This should be fixed now. We'll re-open if this regresses
