### ISSUE TITLE
Renaming Warehouse to Data Exchange

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#129]
Right clicking on project node in project explorer.

(Might be worth a quick but careful Find and Replace on the code for other occurrences)

<img width="453" alt="Screenshot 2024-06-20 at 5 48 18 PM" src="https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/4d6e56b0-2194-4b4e-b411-c0b2647665dc">

**Comment by KellyMWhitehead** [comment]
Want me to add the data exchange logo as well?

**Comment by philipbaileynar** [comment]
Yes. I have in arcpro viewer. 

Do you have it or need it?

**Comment by KellyMWhitehead** [comment]
version 0.9.4
