### ISSUE TITLE
Loads of errors loading VBET Project

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#20]
The issue where this was brought up:
https://github.com/Riverscapes/RiverscapesXML/issues/79

This is related to Joe's video

https://youtu.be/pxwapXjZSMA?t=1143

The project that cannot be loaded is here:
https://data.riverscapes.xyz/#/PUBLIC_DATA/0dc1c4b1-8f5c-4f43-a584-7bf50668fc60

It has something to do with 'id's not being found.

**Comment by KellyMWhitehead** [comment]
Error seems to occur when a project has different (or missing?) id's than what the BL is looking for. Strangely, the error is happening when trying to build the [views](https://github.com/Riverscapes/QRAVEPlugin/blob/fd6b28a7c31680f2cd9d77d19fc83c30df82bb3f/src/classes/project.py#L121)

This is not affecting projects with all expected layers and tags.

**Comment by MattReimer** [comment]
Hmmm. Can we drop a good error into the console logs and fail gracefully?

**Comment by MattReimer** [comment]
Changes look good. I'm closing this.
