### ISSUE TITLE
Update to support more basemap Types (XYZ and TMS)

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#21]
We now have the ability to use more than just WMS baselayers.

We added this to the BaseMaps.xml file here
https://github.com/Riverscapes/RiverscapesXML/pull/85

This request came from an issue requesting Google and Bing baseLayers
https://github.com/Riverscapes/RiverscapesXML/issues/74

filter make sure the layer tile type is being read from Basemaps.xml correctly and then use switch logic to render that layer correctly

ArcRave has a corresponding issue
https://github.com/Riverscapes/RaveAddIn/issues/139

**Comment by MattReimer** [comment]
@KellyMWhitehead if you're looking for a basemaps file to use for testing there's one in RiverscapesXML here
https://github.com/Riverscapes/RiverscapesXML/blob/google_imagery/BaseMaps.xml

**Comment by KellyMWhitehead** [comment]
tested and verified working.

**Comment by joewheaton** [comment]
Hey @KellyMWhitehead and @MattReimer. For me, the XML tiles appear to be working in QRAVE. However, for me, I also have those loaded in my Q Browser → XYZ Tiles. For @shelbysawyer, she was having a weird error message and behavior she lays out in [this video](https://youtu.be/jPSs3EkNkSs). I'm wondering @KellyMWhitehead if you tested this for your machine without having all the XYZ tiles already loaded.

Also, I found [this cool script](https://raw.githubusercontent.com/klakar/QGIS_resources/master/collections/Geosupportsystem/python/qgis_basemaps.py) that has a bunch more services (e.g. ESRI, Open Street Map, Stamen and Strava), which shows the syntax for adding "Sources". I wonder if this gives us a hint about how we can do the same for users (as well as stealing some cool new basemaps)?

**Comment by MattReimer** [comment]
@joewheaton the first thing I'm going to say without even looking is "try upgrading"

Make sure you're at the latest version of the plugin. The last patch fixed a whole bunch of subtle xyz tile problems.

Now I'll go look at the video

**Comment by MattReimer** [comment]
Ok, now I've viewed the video. @shelbysawyer unfortunately QGIS just simply does not handle XYZ tiles very well. When you zoom in and the map goes blank that's the system trying to catch up and download the right tiles. Sometimes that process glitches out and you get nothing but I find that panning the map around or just waiting can sometimes bring it back. 

The video shows adding tiles using QGIS Menu. If you use QRAVE to add those tiles you may end up with a better result. I realize this depends on the tiles you need being available in our QRAVE basemap selection.

<img width="983" alt="Screen Shot 2021-06-24 at 7 36 50 AM" src="https://user-images.githubusercontent.com/1063391/123282186-1fa9dd00-d4bf-11eb-92c3-d5ce409175ec.png">

QGIS is a pretty new tool for us though so we're constantly trying to figure this stuff out. Keep posting when you run into problems and we'll all learn this together.

**Comment by shelbysawyer** [comment]
@MattReimer Gotcha-- thanks for laying that all out. I'm relatively new to QGIS and still figuring out where everything lives, the best paths from A to B for certain tasks, etc. Thanks for the help, and I'll keep posting problems as they arise.

**Comment by MattReimer** [comment]
Closing this as it seems resolved
