### ISSUE TITLE
Raster Transparency Error

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRAVEPlugin#22]
Seeing this often when adding raster layers, I think with transparency.

![Screen Shot 2021-05-24 at 11 07 14 AM](https://user-images.githubusercontent.com/34071692/119389529-98c7d180-bc80-11eb-95bc-5b63e07a7992.png)

**Comment by MattReimer** [comment]
Cool. Thanks for logging this nick. When you attach this can you give me the version of QRAVE you've got and also maybe a project (warehouse link is fine) where you're seeing this?

Just so I don't have to chase any red herrings reproducing.

**Comment by nick4rivers** [comment]
For sure @MattReimer - and also I just tested this again using the most recent version of Q 3.18 and I'm not getting the error. Still getting this error in 3.16 however.

Using QRAVE 0.3.0.

**Comment by MattReimer** [comment]
Ah, glad I asked. 0.4.0 is the latest. Give that a try and close this bug if it still happens

FYI the upgrade notifications are pretty bad. Once the experimental flag is turned off we might see better notifications but if not I might look at a custom update mechanism that bypasses QGis entirely

**Comment by MattReimer** [comment]
@KellyMWhitehead maybe just quickly verify and then close this one. I'm nearly 100% sure it's due to the old version

**Comment by nick4rivers** [comment]
Yes - I believe this is all good. Thanks guys,
