### ISSUE TITLE
Backslashes (windows) break Linux/OSX

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#30]
QRave should be able to handle windows slashes in project files, even on mac.

example:

```
<Raster guid="9e5b9cb9-cbad-40ce-99fd-dbe100552bac" id="DEM">
    <Name>DEM</Name>
    <Path>inputs\dem.tif</Path>
</Raster>
```

On a Mac or linux this will be a path not found.

**Comment by joewheaton** [comment]
So since this fix, we've been using these projects in Windows and not had any problems. I think this can be closed (reopen if someone finds something).
