### ISSUE TITLE
Second project loaded has no views

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#31]
related to https://github.com/Riverscapes/riverscapes-tools/issues/319

This may be a red-herring but it's worth investigating. @joewheaton loaded two VBET projects in QRAVE and the second one had no views listed. If this isn't related to QRAVE and is more of a data issue just close the ticket.

The project loaded was this one:
https://data.riverscapes.xyz/#/PUBLIC_DATA/0dc1c4b1-8f5c-4f43-a584-7bf50668fc60

This could be:

* Something wrong with the project file itself
* Something wrong with how the second project loads into the tree
* Something I can't think of..... (sorry, not helpful 😄 )

![123281102-a31afc80-d4c6-11eb-93dd-05eaa5dd05ef](https://user-images.githubusercontent.com/1063391/123283239-12412280-d4c0-11eb-9f42-f33e1a454749.png)

**Comment by joewheaton** [comment]
I think this has been solved over in https://github.com/Riverscapes/RiverscapesXML/pull/213

If I am wrong, reopen.
