### ISSUE TITLE
Add Business Logic File Path to Console Log

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#42]
It would be super helpful for debugging to have a console log message that states the location of the business logic XML file every time a project is loaded. It speeds up debugging to know categorically whether QRAVE is using the shipped business logic, or the BL adjacent to the project file.

We don't need this in the "green banner" that appears at the top of the map. Just on the QRAVE tab:

<img width="567" alt="Screen Shot 2021-08-24 at 10 58 56 AM" src="https://user-images.githubusercontent.com/8645379/130666426-7381e972-7b65-4f00-9425-8ded387dc9c2.png">

**Comment by MattReimer** [comment]
I thought we did have that. I don't see any "info" messages in the screenshot. Just "warnings". Is it possible that qgis is set to not show anything stronger than a warning?

**Comment by philipbaileynar** [comment]
I see the project load message with the project XML path. Nothing for the BL path, and no place to change notification level.

**Comment by MattReimer** [comment]
I'll take this on. I'm going to need to be in there anyway
