### ISSUE TITLE
setLayerTransparency not working for vector layers

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#46]
Seems like `setLayerTransparency` might be new in the API across versions 

I think I have a fix for this already but it needs testing

**Comment by joewheaton** [comment]
This is a pretty low priority as we have a work-around (i.e. specify transparency in symbology files). Moreover, there is no way to apply this setLayerTransparency in Arc as far as we know.

**Comment by MattReimer** [comment]
Well it's fixed and working so... 😄
