### ISSUE TITLE
Toolbar Icons Disabled upon first install

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#5]
Kinda big deal, because most users won't know how to proceed...

Why can't the default state of these buttons be set to True? There's no situation where these buttons ever need to be disabled.

<img width="1472" alt="Screen Shot 2021-04-30 at 10 17 43 AM" src="https://user-images.githubusercontent.com/8645379/116761766-5c7cba80-a9cd-11eb-88f3-cbdff87595d2.png">

**Comment by MattReimer** [comment]
Yes, there is a case but I take your point about the importance.
