### ISSUE TITLE
Minor Bug - Basemap Added to Map on Top.... should always be on bottom.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRAVEPlugin#64]
I'm loving the new QRAVE 0.7.0. One minor bug that may have cropped up when we correctly fixed [adding new projects to top of tree](https://github.com/Riverscapes/QRAVEPlugin/issues/59) is that basemaps no longer preserve their "proper" place and order at bottom of users Layer TOC. We should check this in ArcRAVE too. 
![image](https://user-images.githubusercontent.com/9723905/139856437-462a355a-327a-4a1d-94ea-5a0a7cd0f1bb.png)

**Comment by joewheaton** [comment]
Can we fix this please? I can't tell you how many thousands of times I find myself wasting time dragging the basemap to the bottom.

**Comment by MattReimer** [comment]
Hmm. we have an as-of-yet unpublished fix for keeping the tree state: a22fca3

But it does look like this issue hasn't been tackled yet. Maybe we should collect together a few of these bugs and do a new version sometime soon.

**Comment by philipbaileynar** [comment]
i have code in QRiS for adding basemaps at the bottom. but i haven't looked into qrave code to see if this is straightforward change.
