### ISSUE TITLE
RIM projects don't open in QRAVE

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/QRAVEPlugin#69]
They open fine in Arc, but in Q I get this error:
![rim_q_error](https://user-images.githubusercontent.com/21687931/148999681-3c457197-de90-41a5-9b5b-ca1cb2b950ff.png)

**Comment by joewheaton** [comment]
@KellyMWhitehead any thoughts?

**Comment by Jdgilby** [comment]
Projects open for me, I have the same version of Q as Jordan.

**Comment by Jdgilby** [comment]
To update that last comment. Some open and some don't.
