### ISSUE TITLE
Error opening projects

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/QRAVEPlugin#75]
Josh and I are both getting this error when opening  projects in QRAVE

`Traceback (most recent call last):
  File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\qrave_toolbar.py", line 355, in projectBrowserDlg
    self.dockwidget.add_project(dialog_return[0])
  File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\dock_widget.py", line 198, in add_project
    basename = test_project.qproject.text()
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by MattReimer** [comment]
Hi @jtgilbert is this all projects or just some? 

Can you link to the warehouse (if that's where you got them) so we can reproduce?

**Comment by jtgilbert** [comment]
@MattReimer I was assuming it was all because Josh and I were opening different projects on different machines. But now I'm downloading BRAT projects and I'm not getting the error but none of the data shows up in the toolbar. It only brings in the project views but there's nothing to add to the map
![qrave_issue](https://user-images.githubusercontent.com/21687931/181806502-989bbd85-18bf-4d9c-9d25-cef3fa8e30c4.PNG)
.

**Comment by MattReimer** [comment]
This was an issue of the V2 xmls interfering with the old version of qrave. They have been removed for now.

If anyone is still experiencing this problem try syncing your resources folder from the help menu. That should fix it.
