### ISSUE TITLE
QRAVE Refresh

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#97]
We need to "refresh" QRAVE now that we have our new Riverscapes visual identity.

# Rename to "Riverscapes Viewer"

QRAVE is now going to be called "Riverscapes Viewer". If we need an acronym we can use "RV" but this won't be front and centre. The number one place this needs to be changed is in the plugin store.

<img width="1278" alt="Screenshot 2023-12-12 at 3 50 09 PM" src="https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/0c7900ac-9b16-4b99-acb0-96b060a20f3a">

# Tool Logo

Apply the new Riverscapes Viewer logo where appropriate. Initial places I spotted it:

- Left end of toolbar
- root of project tree
- layers in Basemaps
- Plugin icon
- About QRAVE

![viewer-icon](https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/6aea2ada-30f5-42c2-94a1-632999a48a11)

# Riverscapes Logo

Apply the Riverscapes logo where more general reference to Riverscapes Consortium is needed.

# Icons

Apply the same icons that I provided for QRiS. I have put the icons here.

https://drive.google.com/drive/folders/1Tuv3dI3nHpkAotV4yvvXPmUgFiJllz50?usp=drive_link

# Change Publish to NAR GIS Account.

1. Ask Matt to remove the old QRAVE plugin from the plugin store. 
2. Publish the new Riverscapes Viewer

**Comment by joewheaton** [comment]
I really like this @philipbaileynar . Big improvement. Please also rename dockable panel to "Riverscapes Viewer".

**Comment by KellyMWhitehead** [comment]
All done for version 0.9.0.
