### ISSUE TITLE
Lingering references to RAVE

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#99]
Note that QRAVE still appears in the QGIS message panel

![CleanShot 2024-01-02 at 16 03 33@2x](https://github.com/Riverscapes/QRAVEPlugin/assets/8645379/982b73dc-5c51-4eaa-bada-253e2a605100)

**Comment by KellyMWhitehead** [comment]
Did another round of QRAVE cleanup. Ready for 0.9.1

**Comment by joewheaton** [comment]
@philipbaileynar when do you forsee the jump to Q Viewer 1.0 out of curiosity?

**Comment by philipbaileynar** [comment]
I don't mind. Thoughts?

**Comment by joewheaton** [comment]
When we have published Riverscapes site

**Comment by MattReimer** [comment]
I've removed more of these references but now I think we should close this. There may still be mentions of qrave in the logs but cleaning them up would mean renaming source files which we should probably not risk for diminishing returns.
